version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: build/Dockerfile
    container_name: app
    ports:
      - "80:80"
    networks:
      - book-library
  postgres:
    image: postgres:14.2
    container_name: postgres
    env_file:
      - configs/.env.local
    environment:
       POSTGRES_USER: ${DB_USER}
       POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - book-library
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - book-library
  grafana:
    image: grafana/grafana-enterprise:8.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - book-library
networks:
  book-library:
    driver: bridge